"""
try:
尝试执行的代码
catch
出现错误的处理
"""

try:
    num = int(input("请输入一个整数"))
#错误的处理的代码
except:
    print("请输入正确的整数")

print("_"*20)
